# -*- coding: utf-8 -*-
"""Day-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfitD_g4x4bSeV7LX7jwyK5UO6EPHC6f
"""

#Create a List, tuple and Dictionary with 5 elements in it and how to access few elements based on the index. Try  with different examples

# Creating a list with 5 elements
my_list = [10, 20, 30, 40, 50]

# Accessing elements by index
print("List:")
print("First element:", my_list[0])
print("Third element:", my_list[2])
print("Last element:", my_list[-1])
print("Second to last element:", my_list[-2])

# Creating a tuple with 5 elements
my_tuple = (100, 200, 300, 400, 500)

# Accessing elements by index
print("\nTuple:")
print("First element:", my_tuple[0])
print("Third element:", my_tuple[2])
print("Last element:", my_tuple[-1])

#Creating a dictionary with 5 elements
my_dict = {"a": 1, "b": 2, "c": 3, "d": 4, "e": 5}

# Accessing elements by key
print("\nDictionary:")
print("Value associated with key 'a':", my_dict["a"])
print("Value associated with key 'c':", my_dict["c"])

