# -*- coding: utf-8 -*-
"""Day-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_z-Y6rpM-3wmazAy5oeoUKfLOoViWS2h
"""

# Declare variables of different data types
integer_variable = 10
float_variable = 3.14
string_variable = "Hello, world!"
boolean_variable = True

# Print each variable and its type
print(f"Integer variable: {integer_variable}, Type: {type(integer_variable)}")
print(f"Float variable: {float_variable}, Type: {type(float_variable)}")
print(f"String variable: {string_variable}, Type: {type(string_variable)}")
print(f"Boolean variable: {boolean_variable}, Type: {type(boolean_variable)}")